[package]
name = "ausseabed-qajson"

# conda dependencies for the package need to duplicate pypi dependencies here,
# they could also have different names, not in this case
[package.run-dependencies]
jsonschema = "*"

[package.build.backend]
name = "pixi-build-python"
version = "*"

## using hatchling as the build backend, so we need to specify it as a host dependency
[package.host-dependencies]
hatchling = "*"

## Workspace below
[workspace]
preview = ["pixi-build"] # needed to enable `pixi build`
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64"]

## These are environment dependencies for the workspace test env
[dependencies]
ausseabed-qajson = { path = "." }
rattler-build = "*"
pytest = "*"
pytest-cov = "*"
ruff = "*"
hatchling = "*"
pip = "*"
pixi-inspect = ">=2.0.0"
mypy = ">=1.19.1,<2"
types-jsonschema = ">=4.26.0.20260202,<5"


[tasks]
pytest = "python -m pytest --cov=ausseabed.qajson --cov-report=term --cov-report=html tests/"

