name: Build Conda Package

on:
  push:
    branches:
      - "main"
      - "kk/*"
    tags:
      - "v.*"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  ci:
    uses: ausseabed/.github/.github/workflows/ci.yaml@main
    # with:
    #     prefix_channel: ${{ vars.PREFIX_CHANNEL }}
    secrets:
        prefix_api_token: ${{ secrets.PREFIX_API_KEY }}
